"""Added games_played column

Revision ID: 1ed8ee666c89
Revises: 84c5b02690d5
Create Date: 2022-05-22 19:42:24.955748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ed8ee666c89'
down_revision = '84c5b02690d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('games_played', sa.Integer(), nullable=True))
    op.drop_index('ix_user_email', table_name='user')
    op.create_index(op.f('ix_user_games_played'), 'user', ['games_played'], unique=False)
    op.drop_column('user', 'email')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.VARCHAR(length=128), nullable=True))
    op.drop_index(op.f('ix_user_games_played'), table_name='user')
    op.create_index('ix_user_email', 'user', ['email'], unique=False)
    op.drop_column('user', 'games_played')
    # ### end Alembic commands ###
